name: Regular Commit

on:
  # Run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  make-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Make a commit
        run: |
          # Current timestamp
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          
          # Update activity log file
          echo "Activity update: $TIMESTAMP" >> activity_log.txt
          
          # Commit the change
          git add activity_log.txt
          git commit -m "Update activity: $TIMESTAMP"
      
      # Push changes with PAT
      - name: Push changes
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main
